### PR TITLE
updated striker

### PR DESCRIPTION
**Pull request by deskos-xp**

### CODE REVIEW

**Comment by thehappydinoa** [comment]
Hey if you are trying to merge please remove the section that say that this is a fork of the original repo from your readme

**Comment by thehappydinoa** [comment]
Also those comments that you added in the harvester is unnecessary

**Comment by thehappydinoa** [comment]
Also I am unsure why you are changing print to logger please explain what is changed in your PR next time

**Comment by deskos-xp** [comment]
had a long day at work... so, move the print operation to the logger operation, and if logging is then actualWrite() is called at the end to print the in memory log.

**Comment by thehappydinoa** [comment]
Um I don't fully understand but that sounds good

**Comment by deskos-xp** [comment]
I left plugins/theHarvester.py as it is as a standalone utility, created plugins/theHarvesterLib.py so that it can be imported as a module. the cmdline args that theHarvester.py had, can be accessed as variables within the class harvester. as an example. 
harvest=theHarvesterLib.harvester()  ; 
harvest.word="bitpay.com"  ;
data=harvest.run() ; 
#data contains the data to be written to the logger as a list
#word corresponds the -d option of theHarvesterLib.py
#-b is provided by harvest.engine 
# you can also, if the the need arises midcode, also do 
harvest.engines.append(new_search_engine) 
# to append a new search engine dynamically
# hope this helps

**Comment by UltimateHackers** [comment]
```
root@blazy:~/Striker# python striker.py -u teamultimate.in
usage: striker.py [-h] [-t TARGET] [-l LOGFILE] [-p PLUGINS_CFG]
striker.py: error: unrecognized arguments: -u teamultimate.in
```
Maybe you aren't verifying the target in the way the base Striker does.

**Comment by UltimateHackers** [comment]
I don't know why but your version is unable to find emails while the base Striker works fine.
Tested on
`jnujaipur.ac.in`

**Comment by UltimateHackers** [comment]
Can you confirm that the script works so I can merge it?

**Comment by bosci** [comment]
Yeah it was as far as the few scans I did.

**Pull request closed without merging**
